{
    "name": "Document Format Unika",
    "summary": """Formatos de documentos para Unika""",
    "version": "15.0.1.0.0",
    "description": """Formatos de documentos para Unika""",
    "author": "Daniel Dominguez",
    "company": "Xtendoo",
    "website": "https://github.com/OCA/edi",
    "category": "Extra Tools",
    "license": "AGPL-3",
    "depends": [
        "sale",
        "mail",
        "account",
        "account_payment_partner",
    ],
    "data": [
        "data/mail_template.xml",
        "views/paper_format/paperformat_invoice.xml",
        "views/invoice/external_layout_boxed_invoice.xml",
        "views/invoice/invoice_view.xml",
        "views/invoice/invoice_document.xml",
        "views/sale/external_layout_boxed_sale.xml",
        "views/sale/report_analysis_sale.xml",
    ],
    "installable": True,
    "auto_install": False,
}
